name: Activity Leaderboard updater

on:
  schedule:
    - cron: "10,40 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4
        with:
          ref: auto-update
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r update_requirements.txt

      - name: Execute Python script
        run: |
          python update_race_leaderboard.py

      - name: Commit files
        run: |
          git config --local user.name "ducanup01"
          git config --local user.email "ducanup01@gmail.com"
          git add .
          sleep 3
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "automatic updater"
            git push origin auto-update --force
          fi